# Generated by Django 2.2.19 on 2021-03-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boooks', '0002_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='card',
            name='published_date',
        ),
    ]
