# Generated by Django 2.2.19 on 2021-03-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boooks', '0003_auto_20210324_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.AddField(
            model_name='characters',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
