# Generated by Django 2.2.19 on 2021-03-25 09:08

import boooks.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boooks', '0005_auto_20210325_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characters',
            name='file',
        ),
        migrations.AddField(
            model_name='characters',
            name='image',
            field=models.ImageField(null=True, storage=boooks.storage.AsyncFileSystemStorage(), upload_to='.', verbose_name='Uploaded image file'),
        ),
    ]
