# Generated by Django 2.2.19 on 2021-03-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boooks', '0006_auto_20210325_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characters',
            old_name='image',
            new_name='file',
        ),
    ]
