# Generated by Django 2.2.19 on 2021-03-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boooks', '0008_auto_20210325_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
