# Generated by Django 2.2.19 on 2021-03-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boooks', '0009_auto_20210325_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('Habitat', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
